linters-settings:
  govet:
    check-shadowing: true

  gocyclo:
    min-complexity: 15

  golint:
    min-confidence: 0.8

  ineffassign: {}

  staticcheck: {}

  errcheck:
    ignore: # Specify functions to ignore error checking
      - fmt.Fprintf
      - fmt.Printf
      - fmt.Println

  goimports:
    local-prefixes: github.com/ngikut-project-sprint/GoGoManager

  unused:
    check-exported: true

  depguard:
    list-type: blacklist # Can be "whitelist" or "blacklist"
    packages:
      - github.com/pkg/errors
    packages-with-error-message:
      github.com/pkg/errors: "Please use the standard errors package instead."

linters:
  disable-all: false
  enable:
    - govet
    - errcheck
    - staticcheck
    - goimports
    - unused
    - ineffassign
    - depguard
    - gocyclo
    - revive
    - misspell
    - nolintlint
    - gocritic
    - gosec
    - loggercheck

run:
  timeout: 10m
  tests: true
  skip-dirs:
    - vendor
    - node_modules
  skip-files:
    - ".*_test\\.go"

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  exclude:
    - "should have comment or be unexported" # Example: disabling for unexported functions
    - "error return value not checked"

output:
  format: colored-line-number # Options: "json", "tab", "checkstyle", "code-climate", etc.
  print-issued-lines: true
