dir: mocks
outpkg: mocks
with-expecter: true
resolve-type-alias: false
issue-845-fix: true
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
packages:
  github.com/ngikut-project-sprint/TutupLapak-File/internal/repository:
    config:
      dir: mocks/repository
    interfaces:
      FileRepository:
  github.com/ngikut-project-sprint/TutupLapak-File/internal/service:
    config:
      dir: mocks/service
    interfaces:
      FileService:
  github.com/ngikut-project-sprint/TutupLapak-File/internal/utils/imageutil:
    config:
      dir: mocks/imageutil
    interfaces:
      ImageCompressor:
      ImageDecoder:
  github.com/ngikut-project-sprint/TutupLapak-File/internal/utils/rwutil:
    config:
      dir: mocks/rwutil
    interfaces:
      Reader:
  github.com/ngikut-project-sprint/TutupLapak-File/internal/utils/validation:
    config:
      dir: mocks/validation
    interfaces:
      FileValidator:
