// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// ValidateFileFunc is an autogenerated mock type for the ValidateFileFunc type
type ValidateFileFunc struct {
	mock.Mock
}

type ValidateFileFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *ValidateFileFunc) EXPECT() *ValidateFileFunc_Expecter {
	return &ValidateFileFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: fileHeader, maxFileSize
func (_m *ValidateFileFunc) Execute(fileHeader *multipart.FileHeader, maxFileSize int64) error {
	ret := _m.Called(fileHeader, maxFileSize)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, int64) error); ok {
		r0 = rf(fileHeader, maxFileSize)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateFileFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ValidateFileFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - fileHeader *multipart.FileHeader
//   - maxFileSize int64
func (_e *ValidateFileFunc_Expecter) Execute(fileHeader interface{}, maxFileSize interface{}) *ValidateFileFunc_Execute_Call {
	return &ValidateFileFunc_Execute_Call{Call: _e.mock.On("Execute", fileHeader, maxFileSize)}
}

func (_c *ValidateFileFunc_Execute_Call) Run(run func(fileHeader *multipart.FileHeader, maxFileSize int64)) *ValidateFileFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*multipart.FileHeader), args[1].(int64))
	})
	return _c
}

func (_c *ValidateFileFunc_Execute_Call) Return(_a0 error) *ValidateFileFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ValidateFileFunc_Execute_Call) RunAndReturn(run func(*multipart.FileHeader, int64) error) *ValidateFileFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewValidateFileFunc creates a new instance of ValidateFileFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidateFileFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidateFileFunc {
	mock := &ValidateFileFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
