// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

type Reader_Expecter struct {
	mock *mock.Mock
}

func (_m *Reader) EXPECT() *Reader_Expecter {
	return &Reader_Expecter{mock: &_m.Mock}
}

// ReadAll provides a mock function with given fields: r
func (_m *Reader) ReadAll(r io.Reader) ([]byte, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ReadAll")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Reader) ([]byte, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(io.Reader) []byte); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Reader) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reader_ReadAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAll'
type Reader_ReadAll_Call struct {
	*mock.Call
}

// ReadAll is a helper method to define mock.On call
//   - r io.Reader
func (_e *Reader_Expecter) ReadAll(r interface{}) *Reader_ReadAll_Call {
	return &Reader_ReadAll_Call{Call: _e.mock.On("ReadAll", r)}
}

func (_c *Reader_ReadAll_Call) Run(run func(r io.Reader)) *Reader_ReadAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader))
	})
	return _c
}

func (_c *Reader_ReadAll_Call) Return(_a0 []byte, _a1 error) *Reader_ReadAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Reader_ReadAll_Call) RunAndReturn(run func(io.Reader) ([]byte, error)) *Reader_ReadAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewReader creates a new instance of Reader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reader {
	mock := &Reader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
