// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// ReadFile is an autogenerated mock type for the ReadFile type
type ReadFile struct {
	mock.Mock
}

type ReadFile_Expecter struct {
	mock *mock.Mock
}

func (_m *ReadFile) EXPECT() *ReadFile_Expecter {
	return &ReadFile_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: r
func (_m *ReadFile) Execute(r io.Reader) ([]byte, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Reader) ([]byte, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(io.Reader) []byte); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Reader) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadFile_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ReadFile_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - r io.Reader
func (_e *ReadFile_Expecter) Execute(r interface{}) *ReadFile_Execute_Call {
	return &ReadFile_Execute_Call{Call: _e.mock.On("Execute", r)}
}

func (_c *ReadFile_Execute_Call) Run(run func(r io.Reader)) *ReadFile_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader))
	})
	return _c
}

func (_c *ReadFile_Execute_Call) Return(_a0 []byte, _a1 error) *ReadFile_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReadFile_Execute_Call) RunAndReturn(run func(io.Reader) ([]byte, error)) *ReadFile_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewReadFile creates a new instance of ReadFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReadFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReadFile {
	mock := &ReadFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
