// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	image "image"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// DecodeImage is an autogenerated mock type for the DecodeImage type
type DecodeImage struct {
	mock.Mock
}

type DecodeImage_Expecter struct {
	mock *mock.Mock
}

func (_m *DecodeImage) EXPECT() *DecodeImage_Expecter {
	return &DecodeImage_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: r
func (_m *DecodeImage) Execute(r io.Reader) (image.Image, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 image.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Reader) (image.Image, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(io.Reader) image.Image); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(image.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Reader) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DecodeImage_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DecodeImage_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - r io.Reader
func (_e *DecodeImage_Expecter) Execute(r interface{}) *DecodeImage_Execute_Call {
	return &DecodeImage_Execute_Call{Call: _e.mock.On("Execute", r)}
}

func (_c *DecodeImage_Execute_Call) Run(run func(r io.Reader)) *DecodeImage_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader))
	})
	return _c
}

func (_c *DecodeImage_Execute_Call) Return(_a0 image.Image, _a1 error) *DecodeImage_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DecodeImage_Execute_Call) RunAndReturn(run func(io.Reader) (image.Image, error)) *DecodeImage_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewDecodeImage creates a new instance of DecodeImage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecodeImage(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecodeImage {
	mock := &DecodeImage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
