// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	bytes "bytes"
	image "image"

	mock "github.com/stretchr/testify/mock"
)

// ImageCompress is an autogenerated mock type for the ImageCompress type
type ImageCompress struct {
	mock.Mock
}

type ImageCompress_Expecter struct {
	mock *mock.Mock
}

func (_m *ImageCompress) EXPECT() *ImageCompress_Expecter {
	return &ImageCompress_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: buffer, img, maxSize
func (_m *ImageCompress) Execute(buffer *bytes.Buffer, img image.Image, maxSize int64) error {
	ret := _m.Called(buffer, img, maxSize)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*bytes.Buffer, image.Image, int64) error); ok {
		r0 = rf(buffer, img, maxSize)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ImageCompress_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ImageCompress_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - buffer *bytes.Buffer
//   - img image.Image
//   - maxSize int64
func (_e *ImageCompress_Expecter) Execute(buffer interface{}, img interface{}, maxSize interface{}) *ImageCompress_Execute_Call {
	return &ImageCompress_Execute_Call{Call: _e.mock.On("Execute", buffer, img, maxSize)}
}

func (_c *ImageCompress_Execute_Call) Run(run func(buffer *bytes.Buffer, img image.Image, maxSize int64)) *ImageCompress_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bytes.Buffer), args[1].(image.Image), args[2].(int64))
	})
	return _c
}

func (_c *ImageCompress_Execute_Call) Return(_a0 error) *ImageCompress_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ImageCompress_Execute_Call) RunAndReturn(run func(*bytes.Buffer, image.Image, int64) error) *ImageCompress_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewImageCompress creates a new instance of ImageCompress. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageCompress(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageCompress {
	mock := &ImageCompress{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
