name: Run Tests

on:
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "1.23.4"

jobs:
  tests:
    name: Test Go Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Unit Tests
        run: go test ./... -v
